### PR TITLE
Final set of asset libzips for release

### PR DESCRIPTION
**Pull request by credd**
Git can't show a diff on libzip files, so if you want to know the particulars of what's going into the assets, please come talk to me.

### CODE REVIEW

**Comment by ajorians** [comment]
Out of curiosity; why do some of the assets ends with "01" whereas others don't:
whydosomehave01attheend

I get that at a time it was a work in progress but if these are the final ones should they all have some number or no number?

**Comment by credd** [comment]
Generally, the reason we have the numbering is so that we can release new assets down the line with the same name and still be able to differentiate them easily. We might want more than one "lock" or "house" or "basicthird" The folders that don't have these are generally entirely made of stuff that's very specific and unlikely to ever have two items with the same name. "Motion Graphics-Lower Thirds" is the weird case in all this because it has both generic titles like "basicthird" and specific ones like "electricbox". Because I know for a fact that we will be releasing a second "basicthird" online, we needed to number at least that asset, and I numbered the rest in that folder so that we weren't telegraphing that there'd be more than one "basicthird" in the future.

FWIW, Kelly Rush has put his :+1: on this libzip.

**Comment by ajorians** [comment]
Just want to make sure this too.  We add some asset; in this case one under "Music Tracks":
addasset

I see in the Media bin it is English "Music Tracks":
seemusictracks

Which is the same text you showed in the foldername:
translatedforfolderbutnotmediabin

And so is this intentional?  I ask because I know we were just translating the foldernames; so I'm not sure if this applies?

**Comment by ajorians** [comment]
Also I believe everybody is on board with these strings not being localized correct; sample below:
newspaper01

sale

right?

**Comment by ajorians** [comment]
:+1: Looks good to me with the time we have :smiley:

**Comment by credd** [comment]
AJ and I talked in person, but for other reviewers: 
- The issue with the folder names showing up in media names is happening because I ran a script to standardize the filenames of all our assets, but unfortunately that script breaks when I run it on our localized libzips -- it's not a great situation but we don't have good alternatives either. If anyone has further questions about that one, let me know.
- For the icons, it is correct that we do not plan to localize those assets -- they come direct from Shutterstock and I don't think we have a way to change the text in them.

**Comment by credd** [comment]
AJ and I talked in person, but for other reviewers: 
- The issue with the folder names showing up in media names is happening because I ran a script to standardize the filenames of all our assets, but unfortunately that script breaks when I run it on our localized libzips -- it's not a great situation but we don't have good alternatives either. If anyone has further questions about that one, let me know.
- For the icons, it is correct that we do not plan to localize those assets -- they come direct from Shutterstock and I don't think we have a way to change the text in them.

**Comment by BingTSC** [comment]
:+1:

**Pull request merged**
